SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS BoxedSet_Item;
DROP TABLE IF EXISTS BoxedSet;
DROP TABLE IF EXISTS RollingStock;
DROP TABLE IF EXISTS Locomotive;
DROP TABLE IF EXISTS Controller;
DROP TABLE IF EXISTS Track;
DROP TABLE IF EXISTS ProductEra;
DROP TABLE IF EXISTS Era;
DROP TABLE IF EXISTS Cart_Item;
DROP TABLE IF EXISTS Order_Line;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Brand;
DROP TABLE IF EXISTS Cart;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Bank_Detail;
DROP TABLE IF EXISTS Address;
DROP TABLE IF EXISTS Permission;
DROP TABLE IF EXISTS Role_Permission;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS User_Role;
DROP TABLE IF EXISTS Login;
DROP TABLE IF EXISTS User;


SET FOREIGN_KEY_CHECKS = 1;